GUIDES = {
    "nachtzuschlag-berechnen.html": {
        "lang": "de", "pair": "en/calculate-night-shift-allowance.html",
        "title": "Nachtzuschlag berechnen: Uhrzeiten, Pausen und Beispiel | Shift Lion",
        "description": "Nachtzuschlag verständlich berechnen: Nachtstunden, Pausen, Stundenlohn und Zuschlagssatz mit einem konkreten Beispiel erklärt.",
        "eyebrow": "Ratgeber Nachtarbeit", "h1": "Nachtzuschlag berechnen: Uhrzeiten, Pausen und Beispiel",
        "intro": "Für den Nachtzuschlag reicht es nicht, nur die gesamte Schichtdauer zu kennen. Entscheidend sind das gültige Nachtzeitfenster, die darin liegenden Arbeitsstunden, die Pausenart und dein persönlicher Zuschlagssatz.",
        "tool": ("Nachtzuschlag direkt berechnen", "/nachtzuschlag-rechner.html"),
        "sections": [
            ("Welche Angaben brauchst du?", ["Beginn und Ende der Schicht", "Beginn und Ende des zuschlagsfähigen Nachtzeitfensters", "Dauer und Art der Pause", "Brutto-Stundenlohn und Zuschlagssatz"]),
            ("So gehst du Schritt für Schritt vor", ["Bestimme zuerst die gesamte Schichtdauer – bei einem Ende am nächsten Morgen über Mitternacht hinweg.", "Ermittle anschließend nur die Überschneidung zwischen Schicht und Nachtzeitfenster.", "Ziehe eine unbezahlte Pause von der bezahlten Zeit und den zuschlagsfähigen Stunden ab.", "Multipliziere die verbleibenden Nachtstunden mit Stundenlohn und Zuschlagssatz."]),
            ("Konkretes Beispiel", ["Schicht: 22:00 bis 06:00 Uhr", "Nachtzeit: 22:00 bis 06:00 Uhr", "Unbezahlte Pause: 30 Minuten", "Stundenlohn: 20 €, Nachtzuschlag: 25 %", "Ergebnis: 7,5 bezahlte Nachtstunden × 20 € × 25 % = 37,50 € Nachtzuschlag. Der Grundlohn beträgt 150 €."]),
            ("Worauf du achten solltest", ["Tarif- oder Arbeitsverträge können andere Nachtzeitfenster und Sätze vorgeben.", "Bei einer bezahlten Pause bleiben Grundlohn und Zuschläge für die Pausenzeit enthalten.", "Sonntags- oder Feiertagszuschläge können sich überschneiden; welche Kombination gilt, hängt von deinen Regeln ab."]),
        ],
        "faqs": [("Wie berechne ich Nachtstunden über Mitternacht?", "Behandle das Schichtende als Uhrzeit des Folgetags und berechne nur die Überschneidung mit dem Nachtzeitfenster."), ("Zählt eine unbezahlte Pause zum Nachtzuschlag?", "Nein. In der Shift-Lion-Berechnung wird sie sowohl vom Grundlohn als auch von den Zuschlägen abgezogen."), ("Ist der Nachtzuschlag immer 25 Prozent?", "Nein. Der gültige Satz kann sich aus Arbeitsvertrag, Tarifvertrag oder betrieblicher Regelung ergeben.")],
        "related": [("Feiertagszuschlag bei Nachtschichten erklären", "/feiertagszuschlag-nachtschicht.html"), ("Arbeitszeit mit Pause berechnen", "/arbeitszeit-mit-pause-berechnen.html"), ("Alle Schichtzulagen gemeinsam berechnen", "/schichtzulagen-rechner.html")],
    },
    "feiertagszuschlag-nachtschicht.html": {
        "lang": "de", "pair": "en/holiday-allowance-night-shift.html",
        "title": "Feiertagszuschlag bei Nachtschicht vor und nach 0 Uhr | Shift Lion",
        "description": "Feiertagszuschlag bei einer Nachtschicht richtig aufteilen: Stunden vor und nach Mitternacht, Pausen und Überschneidungen erklärt.",
        "eyebrow": "Ratgeber Feiertagsarbeit", "h1": "Feiertagszuschlag bei Nachtschichten: vor und nach 0 Uhr",
        "intro": "Eine Nachtschicht kann nur teilweise in einen Feiertag fallen. Deshalb muss die Schicht am Datumswechsel aufgeteilt werden, bevor Feiertagsstunden und weitere Zuschläge berechnet werden.",
        "tool": ("Feiertagszuschlag direkt berechnen", "/feiertagszuschlag-rechner.html"),
        "sections": [
            ("Warum Mitternacht entscheidend ist", ["Ein Kalendertag endet um 24:00 Uhr. Beginnt der Feiertag um 00:00 Uhr, zählen grundsätzlich nur die danach liegenden Stunden zum Feiertagszeitraum – sofern deine geltenden Regeln nichts anderes bestimmen.", "Endet der Feiertag um 24:00 Uhr, gehören die Stunden danach bereits zum Folgetag."]),
            ("Beispiel: Schicht führt in den Feiertag", ["Schicht: 22:00 bis 06:00 Uhr", "Feiertag beginnt um 00:00 Uhr", "Feiertagszeit innerhalb der Schicht: 00:00 bis 06:00 Uhr", "Bei 30 Minuten unbezahlter Pause verbleiben je nach Lage der Pause bis zu 5,5 zuschlagsfähige Feiertagsstunden."]),
            ("Beispiel: Schicht startet am Feiertag", ["Beginnt die Schicht am Feiertag um 22:00 Uhr und endet um 06:00 Uhr, liegen zunächst zwei Stunden im Feiertag. Die Stunden nach 00:00 Uhr gehören zum nächsten Kalendertag."]),
            ("Sonntag, Feiertag und Pause", ["Überschneiden sich Sonntag und Feiertag, kann je nach Regelung nur der höhere, ein kombinierter oder beide Zuschläge gelten.", "Eine unbezahlte Pause reduziert im Rechner Grundlohn und alle aktivierten Zuschläge; eine bezahlte Pause bleibt enthalten."]),
        ],
        "faqs": [("Zählt die ganze Nachtschicht als Feiertagsarbeit?", "Nicht automatisch. Maßgeblich ist zunächst, welcher Teil der Schicht im Feiertagskalendertag liegt."), ("Was passiert mit Stunden nach 0 Uhr?", "Sie gehören zum neuen Kalendertag und werden entsprechend dessen Feiertagsstatus bewertet."), ("Kann zusätzlich Nachtzuschlag entstehen?", "Ja. Nacht- und Feiertagszeit können sich überschneiden; die zulässige Kombination hängt von deinen Regelungen ab.")],
        "related": [("Nachtzuschlag Schritt für Schritt berechnen", "/nachtzuschlag-berechnen.html"), ("Arbeitszeit mit Pause berechnen", "/arbeitszeit-mit-pause-berechnen.html"), ("Alle Schichtzulagen gemeinsam berechnen", "/schichtzulagen-rechner.html")],
    },
    "arbeitszeit-mit-pause-berechnen.html": {
        "lang": "de", "pair": "en/calculate-working-time-with-break.html",
        "title": "Arbeitszeit mit Pause berechnen – Formel und Beispiele | Shift Lion",
        "description": "Arbeitszeit mit Pause berechnen: Bruttozeit, Nettoarbeitszeit, bezahlte und unbezahlte Pause sowie Nachtschichten verständlich erklärt.",
        "eyebrow": "Ratgeber Arbeitszeit", "h1": "Arbeitszeit mit Pause berechnen",
        "intro": "Die Zeit zwischen Arbeitsbeginn und Arbeitsende ist die Bruttozeit. Erst nach der richtigen Behandlung der Pause erhältst du die Nettoarbeitszeit, die für dein persönliches Stundenkonto relevant ist.",
        "tool": ("Arbeitszeit direkt berechnen", "/arbeitszeitrechner.html"),
        "sections": [
            ("Bruttozeit und Nettoarbeitszeit", ["Bruttozeit umfasst den gesamten Zeitraum zwischen Beginn und Ende.", "Eine unbezahlte Pause wird abgezogen. Eine bezahlte Pause bleibt als Arbeitszeit enthalten.", "Formel: Bruttozeit − unbezahlte Pause = Nettoarbeitszeit."]),
            ("Beispiel Tagschicht", ["Arbeitsbeginn: 06:00 Uhr", "Arbeitsende: 14:00 Uhr", "Bruttozeit: 8 Stunden", "Unbezahlte Pause: 30 Minuten", "Nettoarbeitszeit: 7 Stunden 30 Minuten"]),
            ("Beispiel Nachtschicht", ["Bei 22:00 bis 06:00 Uhr liegt das Ende am Folgetag.", "Die Bruttozeit beträgt ebenfalls 8 Stunden. Nach 30 Minuten unbezahlter Pause bleiben 7 Stunden 30 Minuten."]),
            ("Überstunden richtig vergleichen", ["Vergleiche die Nettoarbeitszeit mit deiner Sollzeit je tatsächlich gearbeitetem Tag.", "Mehrarbeit ist nicht automatisch auszahlbare Überzeit; Arbeitsvertrag, Tarifvertrag und Arbeitszeitkonto können eigene Regeln enthalten."]),
        ],
        "faqs": [("Wie rechne ich eine Schicht über Mitternacht?", "Addiere die Zeit bis 24:00 Uhr und die Zeit ab 00:00 Uhr oder behandle das Ende als Folgetag."), ("Wird eine bezahlte Pause abgezogen?", "Nein. Wenn die Pause als bezahlt gilt, bleibt sie in der Nettoarbeitszeit enthalten."), ("Warum weicht mein Zeitkonto ab?", "Betriebliche Rundungen, Sollzeiten und besondere Zeitarten können anders behandelt werden als in einer einfachen Rechnung.")],
        "related": [("Gesamte Arbeitszeit berechnen", "/arbeitszeitrechner.html"), ("Gesetzliche Mindestpause prüfen", "/pausenrechner.html"), ("Ruhezeit zwischen zwei Schichten prüfen", "/ruhezeit-rechner.html")],
    },
    "ueberstunden-auszahlen-oder-freizeit.html": {
        "lang": "de", "pair": "en/overtime-pay-or-time-off.html",
        "title": "Überstunden auszahlen oder Freizeitausgleich? | Shift Lion",
        "description": "Überstunden auszahlen oder durch Freizeit ausgleichen: Bruttowert, Zuschlag und Freizeitfaktor mit Beispielen vergleichen.",
        "eyebrow": "Ratgeber Überstunden", "h1": "Überstunden auszahlen oder Freizeitausgleich?",
        "intro": "Ob Geld oder freie Zeit besser passt, hängt nicht nur vom rechnerischen Wert ab. Entscheidend sind auch dein Arbeitszeitkonto, mögliche Zuschläge, deine Erholung und die geltenden Vereinbarungen.",
        "tool": ("Überstunden direkt vergleichen", "/ueberstunden-rechner.html"),
        "sections": [
            ("Wert einer Auszahlung", ["Grundwert: Überstunden × Brutto-Stundenlohn", "Zuschlag: Grundwert × Zuschlagssatz", "Brutto-Auszahlung: Grundwert + Zuschlag"]),
            ("Beispiel Auszahlung", ["20 Überstunden × 20 € = 400 € Grundwert", "Bei 25 % Zuschlag kommen 100 € hinzu.", "Die geschätzte Brutto-Auszahlung beträgt 500 € vor Steuern und Abgaben."]),
            ("Freizeitausgleich vergleichen", ["Bei Faktor 1 wird jede Überstunde durch eine freie Stunde ausgeglichen.", "Bei Faktor 1,25 ergeben 20 Überstunden insgesamt 25 freie Stunden.", "Prüfe, ob und bis wann die Freizeit tatsächlich genommen werden kann."]),
            ("Was vor der Entscheidung wichtig ist", ["Welche Regelung steht in Arbeits- oder Tarifvertrag?", "Gibt es Fristen oder Obergrenzen im Arbeitszeitkonto?", "Wie wirkt sich eine Auszahlung auf Steuern und Abgaben aus?", "Ist Erholungszeit für dich aktuell wertvoller als die Auszahlung?"]),
        ],
        "faqs": [("Ist die berechnete Auszahlung netto?", "Nein. Der Rechner zeigt einen Bruttowert vor Steuern und Sozialabgaben."), ("Was bedeutet Freizeitfaktor 1,25?", "Aus einer Überstunde werden rechnerisch 1 Stunde und 15 Minuten Freizeitausgleich."), ("Kann ich immer selbst wählen?", "Nicht zwingend. Vertrag, Tarifvertrag oder betriebliche Vereinbarung können die Möglichkeiten festlegen.")],
        "related": [("Stundenlohn berechnen", "/stundenlohn-rechner.html"), ("Arbeitszeit mit Pause", "/arbeitszeit-mit-pause-berechnen.html")],
    },
    "gemeinsame-freie-tage-schichtplan.html": {
        "lang": "de", "pair": "en/find-shared-days-off-shift-plan.html",
        "title": "Gemeinsame freie Tage im Schichtplan finden | Shift Lion",
        "description": "Zwei Schichtrhythmen vergleichen und gemeinsame freie Tage finden: Startdatum, Rhythmus und Kalenderauswertung verständlich erklärt.",
        "eyebrow": "Ratgeber Schichtplanung", "h1": "Gemeinsame freie Tage im Schichtplan finden",
        "intro": "Bei unterschiedlichen Schichtrhythmen ist ein freies Wochenende nicht selbstverständlich. Mit dem richtigen Startdatum und der vollständigen Reihenfolge beider Rhythmen lassen sich gemeinsame freie Tage zuverlässig berechnen.",
        "tool": ("Schichten direkt vergleichen", "/schichten-vergleichen.html"),
        "sections": [
            ("Diese Angaben brauchst du", ["Für beide Personen ein Datum, an dem Tag 1 des Rhythmus sicher gilt", "Die vollständige Reihenfolge aus Früh, Spät, Nacht und Frei", "Den Monat oder Zeitraum, den ihr vergleichen möchtet"]),
            ("So funktioniert der Vergleich", ["Jeder Kalendertag wird einer Position im jeweiligen Rhythmus zugeordnet.", "Nach dem letzten Rhythmustag beginnt die Folge wieder bei Tag 1.", "Ein gemeinsamer freier Tag entsteht nur, wenn beide Positionen an demselben Datum auf Frei stehen."]),
            ("Beispiel mit versetzten Rhythmen", ["Person A beginnt ihren Acht-Tage-Rhythmus am 1. des Monats.", "Person B beginnt einen anderen Rhythmus am 3. des Monats.", "Der Rechner berücksichtigt diese Verschiebung und zeigt die Überschneidungen als Liste und Kalender."]),
            ("Planung im Alltag", ["Prüft gemeinsame freie Tage frühzeitig für Termine, Reisen oder Familienzeit.", "Aktualisiert den Vergleich, wenn sich ein Rhythmus dauerhaft verschiebt.", "Kurzfristige Tausche oder Urlaub müssen zusätzlich berücksichtigt werden."]),
        ],
        "faqs": [("Müssen beide Schichtfolgen gleich lang sein?", "Nein. Unterschiedlich lange Rhythmen können miteinander verglichen werden."), ("Was bedeutet das Startdatum?", "Es ist der Kalendertag, an dem Tag 1 der jeweiligen Schichtfolge beginnt."), ("Kann ich Urlaub eintragen?", "Der einfache Web-Vergleich nutzt den Grundrhythmus. Individuelle Termine und Urlaub lassen sich besser in der App planen.")],
        "related": [("Arbeitstage berechnen", "/arbeitstage-schichtrhythmus-berechnen.html"), ("Online-Schichtplan erstellen", "/schichtplaner-online.html")],
    },
    "arbeitstage-schichtrhythmus-berechnen.html": {
        "lang": "de", "pair": "en/calculate-workdays-shift-rotation.html",
        "title": "Arbeitstage bei 5-, 6-Tage-Woche und Schichtrhythmus | Shift Lion",
        "description": "Arbeitstage für 5-Tage-Woche, 6-Tage-Woche oder individuellen Schichtrhythmus berechnen – mit Feiertagen und Urlaub.",
        "eyebrow": "Ratgeber Arbeitstage", "h1": "Arbeitstage bei 5-, 6-Tage-Woche und Schichtrhythmus berechnen",
        "intro": "Wie viele Arbeitstage ein Zeitraum enthält, hängt vom Arbeitsmodell ab. Eine feste Wochenverteilung wird anders gezählt als ein Rhythmus, der unabhängig vom Wochentag wiederholt wird.",
        "tool": ("Arbeitstage direkt berechnen", "/arbeitstage-rechner.html"),
        "sections": [
            ("5-Tage-Woche", ["Typischerweise werden fünf ausgewählte Wochentage gezählt, häufig Montag bis Freitag.", "Du kannst die tatsächlichen Arbeitstage anpassen, wenn deine Woche anders verteilt ist."]),
            ("6-Tage-Woche", ["Hier werden sechs ausgewählte Wochentage berücksichtigt.", "Der freie Wochentag muss nicht zwingend Sonntag sein und kann im Rechner angepasst werden."]),
            ("Individueller Schichtrhythmus", ["Lege eine vollständige Folge aus Arbeitsschichten und freien Tagen an.", "Wähle ein Referenzdatum für Tag 1.", "Der Rhythmus wiederholt sich anschließend unabhängig von Kalenderwochen."]),
            ("Feiertage und Urlaub", ["Ein Feiertag wird nur dann abgezogen, wenn er auf einen geplanten Arbeitstag fällt und in deinem Modell arbeitsfrei ist.", "Urlaub reduziert ebenfalls nur geplante Arbeitstage.", "Fallen Urlaub und arbeitsfreier Feiertag zusammen, darf der Tag nicht doppelt abgezogen werden."]),
        ],
        "faqs": [("Wie viele Arbeitstage hat ein Monat?", "Das hängt von Monat, Wochentagen, Arbeitsmodell, Feiertagen und individuellen Abwesenheiten ab."), ("Kann ein Feiertag ein Arbeitstag bleiben?", "Ja. Bei Schichtarbeit kannst du Feiertage entsprechend deinem Rhythmus als Arbeitstage behandeln."), ("Warum brauche ich beim Rhythmus ein Referenzdatum?", "Nur damit lässt sich bestimmen, welcher Rhythmustag auf ein bestimmtes Kalenderdatum fällt.")],
        "related": [("Gemeinsame freie Tage im Schichtplan finden", "/gemeinsame-freie-tage-schichtplan.html"), ("Online-Schichtplan erstellen", "/schichtplaner-online.html"), ("Urlaubsanspruch für Schichtarbeit berechnen", "/urlaubsanspruch-rechner.html")],
    },
}

GUIDES.update({
    "en/calculate-night-shift-allowance.html": {
        "lang": "en", "pair": "nachtzuschlag-berechnen.html",
        "title": "Calculate Night Shift Allowance: Hours, Breaks and Example | Shift Lion",
        "description": "Learn how to calculate night allowance from eligible hours, paid or unpaid breaks, hourly wage and your allowance rate.",
        "eyebrow": "Night work guide", "h1": "Calculate night shift allowance: hours, breaks and example",
        "intro": "A night allowance calculation needs more than the total shift length. The eligible night period, overlapping work hours, break type and your applicable rate all matter.",
        "tool": ("Calculate night allowance", "/en/night-allowance-calculator.html"),
        "sections": [("Information you need", ["Shift start and end", "Start and end of the eligible night period", "Break duration and whether it is paid", "Gross hourly wage and allowance percentage"]), ("Calculation steps", ["Calculate the full shift duration, including work across midnight.", "Find only the overlap between the shift and night period.", "Deduct an unpaid break from paid time and eligible allowance hours.", "Multiply eligible hours by hourly wage and the allowance rate."]), ("Worked example", ["Shift and night period: 22:00–06:00", "Unpaid break: 30 minutes", "Hourly wage: €20; night rate: 25%", "7.5 eligible hours × €20 × 25% = €37.50 night allowance; base pay is €150."]), ("Important limitations", ["Contracts and collective agreements may define different night periods or rates.", "Paid breaks remain included in base pay and allowances.", "Sunday and holiday allowances may overlap under separate rules."])],
        "faqs": [("How do I calculate night hours across midnight?", "Treat the end time as the following day and calculate only the overlap with the night period."), ("Does an unpaid break earn night allowance?", "No. Shift Lion deducts it from both base pay and eligible allowances."), ("Is the night rate always 25%?", "No. Your applicable rate may come from a contract, collective agreement or company rule.")],
        "related": [("Explain holiday allowance on night shifts", "/en/holiday-allowance-night-shift.html"), ("Calculate working time with breaks", "/en/calculate-working-time-with-break.html"), ("Calculate all shift allowances together", "/en/schichtzulagen-rechner.html")],
    },
    "en/holiday-allowance-night-shift.html": {
        "lang": "en", "pair": "feiertagszuschlag-nachtschicht.html",
        "title": "Holiday Allowance on Night Shifts Before and After Midnight | Shift Lion",
        "description": "Split a night shift correctly at midnight and calculate holiday hours, breaks and overlapping allowances with clear examples.",
        "eyebrow": "Holiday work guide", "h1": "Holiday allowance on night shifts: before and after midnight",
        "intro": "A night shift may fall only partly on a public holiday. Split the shift at the date change before calculating holiday hours and any overlapping allowances.",
        "tool": ("Calculate holiday allowance", "/en/holiday-allowance-calculator.html"),
        "sections": [("Why midnight matters", ["A calendar day ends at midnight. If the holiday starts at 00:00, the hours after that point initially belong to the holiday period.", "Hours after the holiday ends at midnight belong to the next calendar day, subject to your applicable rules."]), ("Example: shift leads into a holiday", ["Shift: 22:00–06:00", "Holiday begins at 00:00", "Holiday portion: 00:00–06:00", "A 30-minute unpaid break can reduce eligible holiday time to 5.5 hours, depending on how the break is allocated."]), ("Example: shift starts on a holiday", ["If work begins at 22:00 on the holiday and ends at 06:00, the first two hours fall on the holiday. Hours after midnight belong to the next date."]), ("Sunday, holiday and breaks", ["When Sunday and a holiday overlap, your rules may use the higher rate, a combined rate or both rates.", "An unpaid break removes base pay and enabled allowances; a paid break remains included."])],
        "faqs": [("Does the whole night shift count as holiday work?", "Not automatically. First identify the part that lies within the holiday calendar date."), ("What happens to hours after midnight?", "They belong to the new calendar date and follow that date's holiday status."), ("Can night allowance apply as well?", "Yes. Night and holiday periods can overlap, subject to your applicable combination rules.")],
        "related": [("Calculate night allowance step by step", "/en/calculate-night-shift-allowance.html"), ("Calculate working time with breaks", "/en/calculate-working-time-with-break.html"), ("Calculate all shift allowances together", "/en/schichtzulagen-rechner.html")],
    },
    "en/calculate-working-time-with-break.html": {
        "lang": "en", "pair": "arbeitszeit-mit-pause-berechnen.html",
        "title": "Calculate Working Time with Breaks: Formula and Examples | Shift Lion",
        "description": "Calculate gross and net working time with paid or unpaid breaks, including overnight shift examples.",
        "eyebrow": "Working time guide", "h1": "Calculate working time with breaks",
        "intro": "The period from start to finish is gross time. Correctly handling paid and unpaid breaks gives you the net working time used for a personal hours comparison.",
        "tool": ("Calculate working time", "/en/working-time-calculator.html"),
        "sections": [("Gross and net time", ["Gross time covers the full period between start and end.", "Deduct an unpaid break; keep a paid break as working time.", "Formula: gross time − unpaid break = net working time."]), ("Day-shift example", ["06:00–14:00 equals 8 hours gross.", "After a 30-minute unpaid break, net working time is 7 hours 30 minutes."]), ("Night-shift example", ["For 22:00–06:00, the end is on the following day.", "Gross time is still 8 hours; after a 30-minute unpaid break, 7 hours 30 minutes remain."]), ("Comparing overtime", ["Compare net working time with target hours for each completed workday.", "Extra time is not automatically payable overtime; contractual rules may differ."])],
        "faqs": [("How do I calculate a shift across midnight?", "Add the hours before and after midnight or treat the end as occurring on the following day."), ("Do I deduct a paid break?", "No. A paid break remains included in net working time."), ("Why can my employer's time account differ?", "Company rounding, target hours and special time categories may use different rules.")],
        "related": [("Calculate total working time", "/en/working-time-calculator.html"), ("Check the statutory minimum break", "/en/break-calculator.html"), ("Check rest time between two shifts", "/en/rest-period-calculator.html")],
    },
    "en/overtime-pay-or-time-off.html": {
        "lang": "en", "pair": "ueberstunden-auszahlen-oder-freizeit.html",
        "title": "Overtime Pay or Time Off? Compare Both Options | Shift Lion",
        "description": "Compare overtime payout and time off using gross value, premium rate and time-off factor with a practical example.",
        "eyebrow": "Overtime guide", "h1": "Overtime pay or time off?",
        "intro": "The better option is not determined by the amount alone. Your time account, premium, recovery needs and applicable agreements also matter.",
        "tool": ("Compare overtime options", "/en/overtime-calculator.html"),
        "sections": [("Value of a payout", ["Base value: overtime hours × gross hourly wage", "Premium: base value × premium percentage", "Gross payout: base value + premium"]), ("Payout example", ["20 overtime hours × €20 = €400 base value", "A 25% premium adds €100.", "Estimated gross payout: €500 before taxes and contributions."]), ("Comparing time off", ["Factor 1 gives one free hour per overtime hour.", "Factor 1.25 turns 20 overtime hours into 25 free hours.", "Check when the time off can actually be taken."]), ("Questions before deciding", ["What does your contract or collective agreement say?", "Are there deadlines or time-account limits?", "How would a payout be taxed?", "Is recovery time more valuable to you right now?"])],
        "faqs": [("Is the payout net?", "No. The calculator shows a gross amount before taxes and social contributions."), ("What does a factor of 1.25 mean?", "One overtime hour becomes 1 hour and 15 minutes of time off."), ("Can I always choose?", "Not necessarily. Contracts or company agreements may determine the available option.")],
        "related": [("Calculate hourly wage", "/en/hourly-wage-calculator.html"), ("Working time with breaks", "/en/calculate-working-time-with-break.html")],
    },
    "en/find-shared-days-off-shift-plan.html": {
        "lang": "en", "pair": "gemeinsame-freie-tage-schichtplan.html",
        "title": "Find Shared Days Off in Two Shift Schedules | Shift Lion",
        "description": "Compare two shift rotations and find shared days off using correct start dates, complete rotations and a calendar view.",
        "eyebrow": "Shift planning guide", "h1": "Find shared days off in shift schedules",
        "intro": "When two people work different rotations, shared weekends are not guaranteed. Correct start dates and complete sequences make shared days off predictable.",
        "tool": ("Compare shifts now", "/en/compare-shifts.html"),
        "sections": [("Information you need", ["For each person, a date known to be day 1", "The complete sequence of early, late, night and off days", "The month or period to compare"]), ("How comparison works", ["Every calendar date is assigned a position in each rotation.", "After the final rotation day, the sequence begins again.", "A shared day off occurs only when both positions are marked Off."]), ("Example with shifted rotations", ["Person A starts an eight-day rotation on the first day of the month.", "Person B starts another rotation on the third.", "The calculator accounts for the offset and displays matches in a list and calendar."]), ("Using the result", ["Plan appointments, trips or family time early.", "Update the start date if a rotation changes permanently.", "Handle short-notice swaps and leave separately."])],
        "faqs": [("Must both rotations have the same length?", "No. Rotations of different lengths can be compared."), ("What does the start date mean?", "It is the calendar date on which day 1 of that person's rotation begins."), ("Can I include leave?", "The simple web comparison uses the base rotation; personal events and leave are better managed in the app.")],
        "related": [("Calculate workdays", "/en/calculate-workdays-shift-rotation.html"), ("Create an online shift plan", "/en/schichtplaner-online.html")],
    },
    "en/calculate-workdays-shift-rotation.html": {
        "lang": "en", "pair": "arbeitstage-schichtrhythmus-berechnen.html",
        "title": "Calculate Workdays for 5-Day, 6-Day and Shift Rotations | Shift Lion",
        "description": "Calculate workdays for a five-day week, six-day week or custom shift rotation, including holidays and leave.",
        "eyebrow": "Workdays guide", "h1": "Calculate workdays for fixed weeks and shift rotations",
        "intro": "The number of workdays in a period depends on the work model. A fixed weekly pattern is counted differently from a rotation that repeats independently of weekdays.",
        "tool": ("Calculate workdays", "/en/workdays-calculator.html"),
        "sections": [("Five-day week", ["Count five selected weekdays, commonly Monday to Friday.", "Adjust the actual weekdays if your workweek is arranged differently."]), ("Six-day week", ["Count six selected weekdays.", "The regular day off does not have to be Sunday and can be adjusted."]), ("Custom shift rotation", ["Create a full sequence of work shifts and off days.", "Choose a reference date for day 1.", "The rotation then repeats independently of calendar weeks."]), ("Holidays and leave", ["A holiday is deducted only when it falls on a planned workday and is treated as time off.", "Leave also reduces planned workdays only.", "A holiday and leave on the same day must not be deducted twice."])],
        "faqs": [("How many workdays are in a month?", "It depends on the month, weekdays, work model, holidays and personal absences."), ("Can a holiday remain a workday?", "Yes. Shift workers can treat holidays as workdays according to their rotation."), ("Why does a rotation need a reference date?", "It identifies which rotation day applies to each calendar date.")],
        "related": [("Find shared days off in shift schedules", "/en/find-shared-days-off-shift-plan.html"), ("Create an online shift plan", "/en/schichtplaner-online.html"), ("Calculate leave entitlement for shift work", "/en/leave-entitlement-calculator.html")],
    },
})

GUIDES.update({
    "stundenlohn-aus-gehalt-berechnen.html": {
        "lang": "de", "pair": "en/calculate-hourly-wage-from-salary.html", "title": "Stundenlohn aus Monats- oder Jahresgehalt berechnen | Shift Lion", "description": "Stundenlohn aus Monats- oder Jahresgehalt berechnen: Formel, durchschnittliche Monatsstunden und Beispiel verständlich erklärt.", "eyebrow": "Ratgeber Stundenlohn", "h1": "Stundenlohn aus Gehalt berechnen", "intro": "Ein Monatsgehalt lässt sich erst dann sinnvoll vergleichen, wenn die vereinbarte Wochenarbeitszeit einbezogen wird. Daraus entsteht ein rechnerischer Brutto-Stundenlohn.", "tool": ("Stundenlohn direkt berechnen", "/stundenlohn-rechner.html"),
        "sections": [("Die Grundformel", ["Wochenstunden × 52 ÷ 12 = durchschnittliche Monatsstunden.", "Monatsgehalt ÷ durchschnittliche Monatsstunden = Brutto-Stundenlohn."]), ("Konkretes Beispiel", ["Monatsgehalt: 3.200 € brutto", "Wochenarbeitszeit: 40 Stunden", "Durchschnittliche Monatszeit: 173,33 Stunden", "3.200 € ÷ 173,33 = rund 18,46 € brutto pro Stunde."]), ("Jahresgehalt umrechnen", ["Teile das Jahresgehalt zunächst durch zwölf und verwende anschließend dieselbe Formel.", "Regelmäßige Sonderzahlungen solltest du nur einbeziehen, wenn du einen entsprechend erweiterten Vergleich möchtest."]), ("Grenzen des Vergleichs", ["Zuschläge, Überstunden, Boni und unbezahlte Fehlzeiten werden nicht automatisch ergänzt.", "Das Ergebnis ist kein Netto-Stundenlohn und berücksichtigt keine Steuern oder Sozialabgaben."])],
        "faqs": [("Warum wird mit 52 Wochen gerechnet?", "Damit wird die durchschnittliche Jahresarbeitszeit gleichmäßig auf zwölf Monate verteilt."), ("Kann ich Teilzeit berechnen?", "Ja. Verwende einfach deine tatsächliche vertragliche Wochenarbeitszeit."), ("Sind Sonderzahlungen enthalten?", "Nur wenn sie bereits in deinem eingegebenen Jahres- oder Monatswert berücksichtigt sind.")], "related": [("Überstunden vergleichen", "/ueberstunden-auszahlen-oder-freizeit.html"), ("Schichtzulagen verstehen", "/schichtzulagen-berechnen.html")],
    },
    "schichtzulagen-berechnen.html": {
        "lang": "de", "pair": "en/calculate-shift-allowances.html", "title": "Schichtzulagen berechnen: Nacht, Spät, Sonntag und Feiertag | Shift Lion", "description": "Schichtzulagen berechnen: Grundlohn sowie Nacht-, Spät-, Sonn- und Feiertagszuschläge mit Formeln und Beispiel verstehen.", "eyebrow": "Ratgeber Schichtlohn", "h1": "Schichtzulagen berechnen und richtig einordnen", "intro": "Mehrere Zuschlagsarten können in einem Monat zusammenkommen. Für eine nachvollziehbare Schätzung werden Grundlohn und jede Zuschlagsart zunächst getrennt berechnet.", "tool": ("Schichtzulagen direkt berechnen", "/schichtzulagen-rechner.html"),
        "sections": [("Grundlohn zuerst berechnen", ["Gesamtarbeitsstunden × Brutto-Stundenlohn = Grundlohn.", "Die Zuschläge werden anschließend zusätzlich und je Kategorie berechnet."]), ("Formel je Zuschlagsart", ["Zuschlagsstunden × Stundenlohn × Zuschlagssatz = Zuschlagsbetrag.", "Beispiel: 40 Nachtstunden × 20 € × 25 % = 200 € Nachtzuschlag."]), ("Überschneidende Stunden", ["Eine Stunde kann beispielsweise Nacht- und Sonntagsstunde sein.", "Ob beide Zuschläge gezahlt werden oder nur einer gilt, ergibt sich nicht aus der Mathematik, sondern aus den für dich geltenden Regelungen."]), ("Brutto ist nicht Netto", ["Der Rechner addiert Bruttobeträge.", "Steuerfreiheit, Sozialabgaben und tarifliche Besonderheiten werden nicht automatisch bewertet."])],
        "faqs": [("Kann ich eigene Prozentsätze verwenden?", "Ja. Zuschlagssätze unterscheiden sich und sollten passend zu deinen Regelungen eingetragen werden."), ("Dürfen Zuschlagsstunden überlappen?", "Rechnerisch ja. Ob die Zuschläge kombiniert werden dürfen, hängt von Vertrag oder Tarifregelung ab."), ("Berechnet das Tool den Nettolohn?", "Nein. Es zeigt eine unverbindliche Brutto-Schätzung.")], "related": [("Monatlichen Schichtlohn mit mehreren Schichtarten berechnen", "/monats-schichtlohn-rechner.html"), ("Sonntagszuschlag mit eigenem Satz berechnen", "/sonntagszuschlag-rechner.html"), ("Nachtzuschlag Schritt für Schritt berechnen", "/nachtzuschlag-berechnen.html")],
    },
    "schichtplan-online-erstellen.html": {
        "lang": "de", "pair": "en/create-shift-plan-online.html", "title": "Schichtplan online erstellen: Rhythmus, Monats- und Jahresplan | Shift Lion", "description": "Schichtplan online erstellen: Startdatum und Rhythmus richtig festlegen, Monatskalender erzeugen und Jahresplan speichern.", "eyebrow": "Ratgeber Schichtplanung", "h1": "Schichtplan online erstellen", "intro": "Ein wiederkehrender Schichtrhythmus lässt sich mit einem sicheren Startdatum automatisch auf Monate und Jahre übertragen. Entscheidend sind eine vollständige Reihenfolge und die richtige Zuordnung von Tag 1.", "tool": ("Online-Schichtplan erstellen", "/schichtplaner-online.html"),
        "sections": [("Rhythmus vollständig erfassen", ["Trage jeden Tag der Wiederholung als Früh, Spät, Nacht oder Frei ein.", "Nach dem letzten Tag beginnt die Folge wieder bei Tag 1."]), ("Das richtige Startdatum", ["Wähle einen Kalendertag, dessen Position im Rhythmus du sicher kennst.", "Dieses Datum verbindet Tag 1 mit dem Kalender und verhindert eine dauerhafte Verschiebung."]), ("Monats- und Jahresplan", ["Kontrolliere zuerst einen bekannten Monat.", "Erzeuge danach den Jahresplan und speichere oder drucke ihn als PDF."]), ("Wann du den Plan aktualisieren solltest", ["Bei einer dauerhaften Rhythmusänderung muss die Folge neu angelegt werden.", "Kurzfristige Tausche, Urlaub und Krankheit gehören nicht automatisch zum Grundrhythmus."])],
        "faqs": [("Brauche ich ein Konto?", "Nein. Der Online-Schichtplaner kann ohne Registrierung verwendet werden."), ("Kann ich beliebige Rhythmen eingeben?", "Ja. Früh-, Spät-, Nacht- und freie Tage lassen sich in eigener Reihenfolge kombinieren."), ("Kann ich den Plan als PDF speichern?", "Ja. Über die Druckfunktion kann der Monats- oder Jahresplan als PDF gespeichert werden.")], "related": [("Gemeinsame freie Tage finden", "/gemeinsame-freie-tage-schichtplan.html"), ("Arbeitstage im Rhythmus", "/arbeitstage-schichtrhythmus-berechnen.html")],
    },
    "en/calculate-hourly-wage-from-salary.html": {
        "lang": "en", "pair": "stundenlohn-aus-gehalt-berechnen.html", "title": "Calculate Hourly Wage from Monthly or Annual Salary | Shift Lion", "description": "Convert monthly or annual salary into a comparable gross hourly wage using average monthly hours and a clear example.", "eyebrow": "Hourly wage guide", "h1": "Calculate hourly wage from salary", "intro": "A monthly salary becomes comparable only when weekly working hours are included. The result is a calculated gross hourly wage.", "tool": ("Calculate hourly wage", "/en/hourly-wage-calculator.html"),
        "sections": [("Basic formula", ["Weekly hours × 52 ÷ 12 = average monthly hours.", "Monthly salary ÷ average monthly hours = gross hourly wage."]), ("Worked example", ["Monthly salary: €3,200 gross", "Weekly time: 40 hours", "Average monthly time: 173.33 hours", "€3,200 ÷ 173.33 = about €18.46 gross per hour."]), ("Converting annual salary", ["Divide annual salary by twelve first, then use the same formula.", "Include regular bonuses only when you intentionally want an expanded comparison."]), ("Limits", ["Allowances, overtime, bonuses and unpaid absences are not added automatically.", "The result is not a net wage and excludes taxes and contributions."])],
        "faqs": [("Why use 52 weeks?", "It distributes average annual working time across twelve months."), ("Can I calculate part-time work?", "Yes. Enter your actual contractual weekly hours."), ("Are bonuses included?", "Only if they are already included in the salary value you enter.")], "related": [("Compare overtime", "/en/overtime-pay-or-time-off.html"), ("Understand shift allowances", "/en/calculate-shift-allowances.html")],
    },
    "en/calculate-shift-allowances.html": {
        "lang": "en", "pair": "schichtzulagen-berechnen.html", "title": "Calculate Shift Allowances for Nights, Sundays and Holidays | Shift Lion", "description": "Calculate base pay and night, late, Sunday and holiday allowances using clear formulas and a practical example.", "eyebrow": "Shift pay guide", "h1": "Calculate and understand shift allowances", "intro": "Several allowance types can occur in one month. For a transparent estimate, calculate base pay and each allowance category separately.", "tool": ("Calculate shift allowances", "/en/schichtzulagen-rechner.html"),
        "sections": [("Calculate base pay first", ["Total working hours × gross hourly wage = base pay.", "Each allowance is then calculated separately and added."]), ("Formula for each allowance", ["Eligible hours × hourly wage × rate = allowance amount.", "Example: 40 night hours × €20 × 25% = €200 night allowance."]), ("Overlapping hours", ["An hour can be both a night and Sunday hour.", "Whether both allowances are payable depends on applicable rules rather than the arithmetic."]), ("Gross is not net", ["The calculator adds gross amounts.", "Tax exemptions, contributions and contractual rules are not assessed automatically."])],
        "faqs": [("Can I use custom percentages?", "Yes. Enter the rates that apply to your situation."), ("Can allowance hours overlap?", "Mathematically yes; whether rates may be combined depends on your rules."), ("Does the tool calculate net pay?", "No. It provides a non-binding gross estimate.")], "related": [("Calculate monthly shift pay across several shift types", "/en/monthly-shift-pay-calculator.html"), ("Calculate Sunday allowance with your own rate", "/en/sunday-allowance-calculator.html"), ("Calculate night allowance step by step", "/en/calculate-night-shift-allowance.html")],
    },
    "en/create-shift-plan-online.html": {
        "lang": "en", "pair": "schichtplan-online-erstellen.html", "title": "Create a Shift Plan Online: Rotation, Month and Year | Shift Lion", "description": "Create an online shift plan by setting the correct start date and rotation, then generate monthly and yearly calendars.", "eyebrow": "Shift planning guide", "h1": "Create a shift plan online", "intro": "A repeating rotation can be extended across months and years from one reliable start date. A complete sequence and correct day-one assignment are essential.", "tool": ("Create an online shift plan", "/en/schichtplaner-online.html"),
        "sections": [("Enter the complete rotation", ["Assign every day in the sequence as Early, Late, Night or Off.", "After the final day, the rotation starts again at day 1."]), ("Choose the correct start date", ["Use a calendar date whose position in the rotation you know.", "This connects day 1 to the calendar and prevents a permanent offset."]), ("Month and year views", ["Check a familiar month first.", "Then generate the yearly plan and save or print it as a PDF."]), ("When to update the plan", ["A permanent rotation change requires a new sequence.", "Short-notice swaps, leave and sickness are not part of the repeating base pattern."])],
        "faqs": [("Do I need an account?", "No. The online planner works without registration."), ("Can I enter any rotation?", "Yes. Combine early, late, night and off days in your own order."), ("Can I save the plan as a PDF?", "Yes. Use the print function to save the monthly or yearly plan as a PDF.")], "related": [("Find shared days off", "/en/find-shared-days-off-shift-plan.html"), ("Calculate workdays", "/en/calculate-workdays-shift-rotation.html")],
    },
})
