import html


PAGES = {"fuer-schichtarbeiter.html": "de", "en/for-shift-workers.html": "en"}


def render(path):
    en = PAGES[path] == "en"
    home = "/en/" if en else "/"
    tools = "/en/tools/" if en else "/tools/"
    method = "/en/methodology.html" if en else "/methodik.html"
    guides = "/en/guides/" if en else "/ratgeber/"
    app = "/download/android/"
    sectors = [
        ("Healthcare & emergency services" if en else "Pflege & Rettungsdienst", "Night shifts, changing rosters and short recovery windows need a clear overview." if en else "Nachtdienste, wechselnde Pläne und kurze Erholungsfenster brauchen einen klaren Überblick.", [("Night allowance" if en else "Nachtzuschlag", "/en/night-allowance-calculator.html" if en else "/nachtzuschlag-rechner.html"), ("Rest period" if en else "Ruhezeit", "/en/rest-period-calculator.html" if en else "/ruhezeit-rechner.html"), ("Compare shifts" if en else "Schichten vergleichen", "/en/compare-shifts.html" if en else "/schichten-vergleichen.html")]),
        ("Fire services & security" if en else "Feuerwehr & Sicherheit", "Long and rotating duties make reliable planning of work and shared time especially valuable." if en else "Lange und rotierende Dienste machen verlässliche Planung von Arbeit und gemeinsamer Zeit besonders wertvoll.", [("Online shift planner" if en else "Online-Schichtplaner", "/en/schichtplaner-online.html" if en else "/schichtplaner-online.html"), ("Workdays" if en else "Arbeitstage", "/en/workdays-calculator.html" if en else "/arbeitstage-rechner.html"), ("Shared days off" if en else "Gemeinsame freie Tage", "/en/compare-shifts.html" if en else "/schichten-vergleichen.html")]),
        ("Manufacturing & logistics" if en else "Produktion & Logistik", "Early, late, night, Sunday and holiday work can be estimated with your own contractual rates." if en else "Früh-, Spät-, Nacht-, Sonn- und Feiertagsarbeit lassen sich mit den eigenen Vertragssätzen einschätzen.", [("Monthly shift pay" if en else "Monats-Schichtlohn", "/en/monthly-shift-pay-calculator.html" if en else "/monats-schichtlohn-rechner.html"), ("Shift allowances" if en else "Schichtzulagen", "/en/schichtzulagen-rechner.html" if en else "/schichtzulagen-rechner.html"), ("Break calculator" if en else "Pausenrechner", "/en/break-calculator.html" if en else "/pausenrechner.html")]),
    ]
    cards = "".join(f'<article><h2>{html.escape(title)}</h2><p>{html.escape(copy)}</p><div class="links">'+"".join(f'<a href="{href}">{html.escape(label)} →</a>' for label, href in links)+"</div></article>" for title, copy, links in sectors)
    title = "Shift work tools, planners and guides" if en else "Schichtarbeit: Rechner, Schichtplaner und Ratgeber"
    description = "Free calculators, planning tools and practical guides for shift workers in healthcare, emergency services, security, manufacturing and logistics." if en else "Kostenlose Rechner, Planungshilfen und Ratgeber für Schichtarbeiter in Pflege, Rettungsdienst, Sicherheit, Produktion und Logistik."
    goals = """<section><span class="section-kicker">WHAT DO YOU WANT TO DO?</span><h2>Start with your current question</h2><div class="goal-grid"><a href="/en/schichtplaner-online.html"><strong>Create a shift plan</strong><small>Turn your rotation into a monthly or yearly calendar.</small></a><a href="/en/schichtzulagen-rechner.html"><strong>Estimate allowances</strong><small>Calculate night, Sunday, holiday and other premiums.</small></a><a href="/en/compare-shifts.html"><strong>Find shared days off</strong><small>Compare two rotations directly in the browser.</small></a><a href="/download/android/"><strong>Keep the plan in the app</strong><small>Add duties, appointments and days off on your phone.</small></a></div></section>""" if en else """<section><span class="section-kicker">WAS MÖCHTEST DU ERLEDIGEN?</span><h2>Starte mit deiner aktuellen Frage</h2><div class="goal-grid"><a href="/schichtplaner-online.html"><strong>Schichtplan erstellen</strong><small>Deinen Rhythmus als Monats- oder Jahreskalender anzeigen.</small></a><a href="/schichtzulagen-rechner.html"><strong>Zuschläge einschätzen</strong><small>Nacht-, Sonn-, Feiertags- und weitere Zuschläge berechnen.</small></a><a href="/schichten-vergleichen.html"><strong>Gemeinsame freie Tage finden</strong><small>Zwei Schichtrhythmen direkt im Browser vergleichen.</small></a><a href="/download/android/"><strong>Plan in der App behalten</strong><small>Dienste, Termine und freie Tage auf dem Smartphone ergänzen.</small></a></div></section>"""
    return f'''<!doctype html><html lang="{'en' if en else 'de'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | Shift Lion</title><meta name="description" content="{description}"><link rel="canonical" href="https://shiftlion.app/{path}"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/trust.css?v=1"><link rel="stylesheet" href="/reach.css?v=2"></head><body><header><nav><a class="logo" href="{home}"><img src="/Shift-Lion-Logo-groß.png" alt="Shift Lion" width="852" height="456"></a><div><a href="{home}">{'Home' if en else 'Startseite'}</a><a href="{tools}">{'All tools' if en else 'Alle Tools'}</a><a href="{guides}">{'Guides' if en else 'Ratgeber'}</a><a href="{app}">{'Download app' if en else 'App herunterladen'}</a></div></nav><div class="hero-copy"><span>{'BUILT FOR SHIFT WORK' if en else 'FÜR SCHICHTARBEIT GEMACHT'}</span><h1>{title}</h1><p>{description}</p><div class="hero-actions"><a class="primary" href="{tools}">{'Open free tools' if en else 'Kostenlose Tools öffnen'}</a><a class="secondary" href="{app}">{'Download app' if en else 'App herunterladen'}</a></div></div></header><main>{goals}<div class="section-heading"><span class="section-kicker">{'BY PROFESSION' if en else 'PASSEND ZUM BERUF'}</span><h2>{'Useful tools for your work pattern' if en else 'Hilfreiche Tools für deinen Arbeitsrhythmus'}</h2></div><section class="sector-grid">{cards}</section><section><h2>{'Why Shift Lion?' if en else 'Warum Shift Lion?'}</h2><div class="principles"><article><strong>{'No registration' if en else 'Ohne Anmeldung'}</strong><p>{'Calculators work directly in the browser.' if en else 'Die Rechner funktionieren direkt im Browser.'}</p></article><article><strong>{'Transparent' if en else 'Nachvollziehbar'}</strong><p>{'Formulas, limits and sources are visible.' if en else 'Formeln, Grenzen und Quellen sind sichtbar.'}</p></article><article><strong>{'Made for rotations' if en else 'Für Rhythmen gedacht'}</strong><p>{'Tools and app understand rotating work patterns.' if en else 'Tools und App berücksichtigen wechselnde Arbeitsmuster.'}</p></article></div></section></main><footer><a href="{tools}">{'All tools' if en else 'Alle Tools'}</a><a href="{guides}">{'Guides' if en else 'Ratgeber'}</a><a href="{method}">{'Methodology' if en else 'Methodik'}</a><a href="mailto:masterinpocket@gmail.com">{'Contact' if en else 'Kontakt'}</a><small>© 2026 Shift Lion · Master in Pocket</small></footer></body></html>'''
